- Dockerfile
Build folder is nice to have already so that there's a place to bind HTTP server to.
> Create build directory in container

- src/actions/documentActions.js
- src/components/input/File.js
- src/components/projectDocuments/Document.js
- src/components/projectDocuments/DocumentGroup.js
- src/components/projectDocuments/ProjectDocuments.scss
- src/components/projectDocuments/index.js
- src/reducers/documentReducer.js
- src/sagas/commentSaga.js
- src/sagas/documentSaga.js
- src/selectors/documentSelector.js
- src/selectors/projectSelector.js
- src/services/documentService.js
Added fetching and downloading of documents.
> Document page

- public/locales/fi/translation.json
- src/components/projectCard/Description.js
- src/components/projectCard/Documents.js
- src/components/projectCard/StrategyConnection.js
- src/components/projectCard/Timetable.js
- src/components/projectCard/projectCard.scss
Aikaisemmin projektikortin laatikot olivat tyhjät, jos dataa ei ollut vielä syötetty. Nyt projektikortin laatikoissa näkyy "Tietoja ei ole vielä syötetty" teksti tyhjän sijaan.
> Lisätty tyhjille projektikortin laatikoille informoivat tekstit

- src/utils/userManager.js
fixed silent renew to actually renew session and not throw error
> Kaav 380 Sessio vanhenee satunnaisesti

- package.json
- src/components/App.js
- src/components/auth/IdleMonitor.js
- src/components/auth/InactiveMessage.js
- src/hooks/IsMounted.js
-Notification and ability to continue session if user has been inactive for long time.
> KAAV-443 Sessio huomautus ei aktiiviselle käyttäjälle

- src/components/common/LoggingComponent.js
-Fieldset values to show only recently modified fields on last modified info view instead of all ever modified values.
> KAAV-407 Tarkistettava, jääkö pääkäyttäjän tekemistä tietokenttä-muutoksista lokitieto

- src/actions/projectActions.js
- src/components/RichTextEditor/index.js
- src/components/common/Common.scss
- src/components/input/CustomField.js
- src/components/input/CustomInput.js
- src/components/input/CustomTextArea.js
- src/components/input/FieldSet.js
- src/components/input/FormField.js
- src/components/input/Input.scss
- src/components/input/SelectInput.js
- src/components/projectEdit/EditForm.js
- src/components/projectEdit/FormSection.js
- src/components/projectEdit/index.js
- src/reducers/projectReducer.js
- src/sagas/projectSaga.js
- src/selectors/projectSelector.js
- src/utils/api.js
lock and unclock front integrated to backend
> Kaav 497 Muokkauksen lukitus

- src/components/input/CustomInput.js
- src/components/input/FormField.js
bug fixes on creating new project
> KAAV-559 uuden projektin luonti ei onnistu

- src/components/RichTextEditor/index.js
- src/components/input/CustomField.js
- src/components/input/CustomInput.js
- src/components/input/SelectInput.js
changed owner information to be the main source for unlocking and locking
> KAAV-498-fixes-2

- src/components/RichTextEditor/index.js
- src/components/input/CustomField.js
- src/components/input/CustomInput.js
- src/components/input/SelectInput.js
Removed lock and unclock from select fields because customer requested. Added readonly to trigger to custominput and richtextfield if not owner and trying to edit field
> KAAV-497-modifications.

- src/components/input/CustomField.js
- src/components/input/FieldSet.js
- src/components/input/FormField.js
individual fielset input to have locked/unlocked style
> KAAV-497 individual fielset input to have locked/unlocked style

- src/components/RichTextEditor/index.js
richtext editors to unlock if closing tab and editing field
> KAAV-497 richtext editors to unlock if closing tab and editing field

- src/components/projectList/index.js
sort state to start from -modifiedat
> KAAV-592 Omat projektit toteutus frontend

- src/components/input/CustomField.js
- src/components/input/Input.scss
- src/components/input/SelectInput.js
- src/components/projectList/List.js
- src/components/projectList/OwnProjectFilters.js
-Select type inputs to have lock/unlock
-Project view spinner improvement
-Project view unit filter not to call backend if no value has changed when opening/closing dropdown
> KAAV-469 Muokattavan kentän lukitus

- src/actions/projectActions.js
- src/components/RichTextEditor/index.js
- src/components/input/CustomField.js
- src/components/input/CustomInput.js
- src/components/input/CustomTextArea.js
- src/components/input/FieldSet.js
- src/components/input/FormField.js
- src/components/projectEdit/EditForm.js
- src/components/projectEdit/FormSection.js
- src/components/projectEdit/index.js
- src/components/projectEdit/quickNav/QuickNav.js
- src/components/projectList/List.js
- src/components/projectList/index.js
- src/reducers/projectReducer.js
- src/sagas/projectSaga.js
- src/utils/api.js
- src/utils/authUtils.js
-Removed pw number field from own projects table.
-Own projects to fetch projects where one is expert and other roles not just main user with ad id.
-Unlock all fields front.
-Utility function to get current ad user id.
> KAAV-469 Lock field imrpovements, KAAV-474  own projects modifications

- src/components/RichTextEditor/index.js
- src/components/input/CustomInput.js
- src/components/input/SelectInput.js
- src/components/projectEdit/index.js
-Lock field call to update data value for input, richtext and select
> KAAV-589 Lukitustiedon mukana päivitetään data kenttään frontend

- package.json
- src/components/auth/IdleMonitor.js
- src/components/common/Common.scss
- src/components/common/colors.scss
- src/components/input/FormField.js
- src/components/input/Input.scss
- src/components/projectEdit/EditForm.js
- src/components/projectEdit/FormFilter.js
- src/components/projectEdit/FormSection.js
- src/components/projectEdit/ProjectEdit.scss
- src/components/projectEdit/index.js
- src/components/projectEdit/quickNav/QuickNav.js
- src/components/projectEdit/quickNav/styles.scss
- yarn.lock
-Toiminnallisuudet navigaatio
-Toiminnallisuudet roolipohjainen suodatus
-sticky header ja suodatus
> KAAV-640  Roolipohjainen suodatus FE toiminnallisuudet.  KAAV-642  Navigaatiorakenne FE toteutus toiminnallisuudet

- src/components/common/colors.scss
- src/components/projectEdit/EditForm.js
- src/components/projectEdit/FormFilter.js
- src/components/projectEdit/FormSection.js
- src/components/projectEdit/ProjectEdit.scss
- src/components/projectEdit/index.js
- src/components/projectEdit/quickNav/QuickNav.js
- src/components/projectEdit/quickNav/styles.scss
-Checked tags to dissapear when all tags removed.
-Total tag count to show total not the current sections count.
-Nav button hover colors to show correct color on certain phase/section.
-No results message never dissapears fix.
> KAAV-710 bug fixes

- src/components/RichTextEditor/index.js
-No new lock call when same user is switching browser tab windows and editing same field bug fix.
> KAAV-497 muokkauksen lukitus

- src/components/projectEdit/index.js
- src/components/projectEdit/quickNav/QuickNav.js
- src/components/projectEdit/quickNav/styles.scss
-Phase statuses to show up on navigation.
> KAAV-640 Roolipohjainen suodatus frontend

- src/actions/projectActions.js
- src/components/RichTextEditor/index.js
- src/components/input/CustomInput.js
- src/components/project/EditFloorAreaFormModal/index.js
- src/components/projectEdit/index.js
- src/reducers/projectReducer.js
- src/sagas/projectSaga.js
- src/selectors/projectSelector.js
-Lock functionality gives errors on forms that is should not be used fix.
-Floor area modal saving does not work fix.
> KAAV-663  Kerrosalatietojen päivitys epäonnistui

- src/actions/projectActions.js
- src/components/project/EditProjectTimetableModal/index.js
- src/components/projectEdit/index.js
- src/reducers/projectReducer.js
- src/sagas/projectSaga.js
- src/selectors/projectSelector.js
Timetable saving not closing modal when saving is done fix
> KAAV-746   Aikataulut päivitys epäonnistuu eikä sulje formia onnistuessa.

- public/locales/fi/translation.json
- src/actions/projectActions.js
- src/components/common/Common.scss
- src/components/common/colors.scss
- src/components/input/FormField.js
- src/components/project/index.js
- src/components/projectDocuments/Document.js
- src/components/projectDocuments/DocumentGroup.js
- src/components/projectDocuments/ProjectDocuments.scss
- src/components/projectDocuments/index.js
- src/components/projectEdit/ProjectEdit.scss
- src/components/projectEdit/index.js
- src/components/projectEdit/quickNav/QuickNav.js
- src/components/projectEdit/quickNav/styles.scss
- src/index.scss
- src/utils/projectUtils.js
-Checking and showing required fields from project edit logic.
-Documents preview, download, closed rights logic for different users and project states.
-styles etc.
> KAAV-647 phase closing functionalities

- src/components/input/CustomInput.js
- src/components/projectDocuments/Document.js
- src/components/projectDocuments/DocumentGroup.js
document load buttons are clickable for a moment on page load fix, date field values not changing fix, debugs for input field
> KAAV-827 Vaiheen sulkeminen - documenttien lataus tarkistus

- src/components/projectDocuments/DocumentGroup.js
- src/utils/projectUtils.js
-Added more required confirmation fields for schedule rule for downloading documents, modified logic for checking is document ready for download.
> KAAV-598 Vaiheen sulkeminen

- src/components/projectEdit/quickNav/QuickNav.js
- src/components/projectEdit/quickNav/styles.scss
-navigation to have size and scroll y, navigation style modifications, added missing color styles for navigation hovers.
> KAAV-737 Navigaation koko

- public/locales/fi/translation.json
- src/actions/projectActions.js
- src/components/common/Common.scss
- src/components/common/Header.js
- src/components/project/index.js
- src/components/projectEdit/ProjectEdit.scss
- src/reducers/projectReducer.js
- src/sagas/projectSaga.js
- src/selectors/projectSelector.js
-Edit page header.
-Header informs last save status and time.
-Save fail and revovery toastr.
> KAAV-478 Automaattinen tallennus varmuus

- src/components/projectEdit/index.js
- src/components/projectEdit/quickNav/QuickNav.js
-phase color modifications to quicknav
> KAAV-755 Sivunavigaatio - kaavan vaiheen värit tulee muuttaa visuaalisen suunnittelun mukaisiksi

- src/components/projectEdit/index.js
- src/components/projectEdit/quickNav/QuickNav.js
-Check/close phase form error message fixes
> KAAV-797 Vaiheen sulkeminen, staattinen virheilmoitus ei ole HDS mukainen

- src/components/input/CustomInput.js
-input not editable after certain scenario of locking and unlocking fix
> KAAV-822 Muokkauksen lukitus - Text input

- src/components/RichTextEditor/index.js
- src/components/input/Input.scss
- src/sagas/projectSaga.js
-richtext editor no double click when focusing to text area from select input.
-as effect from fix above, prevent users from editing locked richtext.
> KAAV-823 Text area joutuu joskus tuplaklikkailemaan että saa focuksen

- public/locales/fi/translation.json
- src/components/common/Common.scss
- src/components/input/File.js
-File upload/download area description and text changes.
> KAAV-746 Tiedoston liittämisen muutokset

- src/components/projectEdit/index.js
- src/components/projectEdit/quickNav/QuickNav.js
-When closing phase open next phase fields and update states for next phase.
> KAAV-861 Käynnistysvaiheen "lopettaminen" ei aloita OAS-vaihetta

- src/components/projectEdit/index.js
-Document refresh to not prevent phase close
> KAAV-850 Projektin voi sulkea, vaikka asiakirjoja ei ole ladattu

- public/locales/fi/translation.json
- src/components/common/Common.scss
- src/components/common/Header.js
- src/components/input/Input.scss
- src/components/projectEdit/ProjectEdit.scss
-Fieldset unable to save error toastr logic for showing and getting data.
-Styles for cannot save toastr modifications.
-Checkbox clickbox too small bug fix.
> KAAV-478 Automaattinen tallennus frontend

- src/components/projectEdit/FormFilter.js
- src/components/projectEdit/index.js
-Filter highligh to get removed if the item is unchecked and checked again from filters menu.
> KAAV-753 Suodatuksen korostus jää päälle, jos suottimen poistaa

- src/components/projectEdit/quickNav/QuickNav.js
-Current phase section selection from navigation to stay in memory if leaving to project car and navigating back
> KAAV-760 Vaiheen vaihtaminen - näkymään tuleminen + focus valikon ulkopuolella

- src/components/common/Header.js
- src/components/projectEdit/quickNav/styles.scss
.Navigation tab focus fix.
-Back button to go from edit page to project card.
> KAAV-736 Kenttien scroll position

- src/components/RichTextEditor/index.js
- src/components/auth/IdleMonitor.js
- src/components/auth/InactiveMessage.js
- src/components/projectEdit/quickNav/QuickNav.js
-Added programmatically blur when richtext is editable and clicking buttons outside the component. Not happening by default for some reason.
> KAAV-607 Richtext editor focus/blur toiminnallisuus tuunaus

- src/components/RichTextEditor/styles.scss
-Richtext editor outline around whole component
> KAAV-606 Richtext editor outline koko editorin mukaan ei vain placeholderille

- src/components/common/Common.scss
- src/components/input/FormField.js
- src/components/input/Input.scss
> KAAV-961 Tiedon visualisointi muokattavan kentän lukinta muutokset

- src/components/common/Common.scss
- src/components/input/FormField.js
- src/components/input/Info.js
- src/components/input/Input.scss
KAAV-966, KAAV-936 info box visual changes and bug fix infobar is under sticky section  header
> KAAV-936 Elementti peittää tekstiä / Graafisten elementtien viimeistelytarve

- src/components/common/NavHeader.js
- src/components/project/index.js
- src/sagas/projectSaga.js
KAAV-960 error handling to chekc if status is missing and show main part of error in that case when creating project. 
KAAV-971 Logic for pw links when they are implemented from excel and backend
> KAAV-960 Spinneri pyörii, konsolissa näkyy virheitä

- src/components/RichTextEditor/index.js
- src/components/input/CustomInput.js
- src/selectors/projectSelector.js
-Make field that user is saving read only for that same user until saving is done. 
-Prevents old data fetch from db before the new data is saved.
-Richtext and text input.
> KAAV-965 Lukitus tarkistuksen mukana päivitetty tieto päivittää vanhaa dataa

- src/components/RichTextEditor/index.js
- src/components/common/Common.scss
- src/components/common/CustomFooter.js
- src/components/common/colors.scss
- src/components/input/CustomField.js
- src/components/input/FieldSet.js
- src/components/input/Input.scss
- src/components/projectEdit/ProjectEdit.scss
-fieldset changes and hide footer from edit view
> KAAV-962 Tiedon visualisointi Fieldset muutokset

- src/assets/icons/angle-down.svg
- src/assets/icons/angle-up.svg
- src/components/RichTextEditor/index.js
- src/components/common/Common.scss
- src/components/common/Header.js
- src/components/common/colors.scss
- src/components/input/CustomField.js
- src/components/input/CustomInput.js
- src/components/input/FieldSet.js
- src/components/input/Input.scss
- src/components/input/SelectInput.js
- src/components/projectEdit/ProjectEdit.scss
- src/hooks/OutsideClick.js
- src/sagas/apiSaga.js
- src/sagas/projectSaga.js
-Custom accordian.
-Fieldset own lock logics.
> KAAV-962 fieldset lock change

- src/components/projectEdit/quickNav/QuickNav.js
-XL phase document download and phase closing issues fixed.
-Nav check fields button not to popup close phase modal.
> KAAV-996 Dokumentteja ei voi ladata ulos

- src/components/common/NavHeader.js
- src/components/input/FormField.js
- src/components/input/Input.scss
- src/components/project/EditProjectModal/NewProjectFormModal.js
- src/components/project/index.js
-PW link to general info card.
Other:
-Create project name input always to be editable.
-Edit project timetable checkbox to show correctly.
> KAAV-971 Tiedon visualisointi - Projektin oleelliset tiedot

- src/components/common/Common.scss
- src/components/projectEdit/EditForm.js
- src/components/projectEdit/FormSection.js
- src/components/projectEdit/ProjectEdit.scss
> KAAV-973 Tiedon visualisointi - Ingressi

- public/locales/fi/translation.json
- src/components/input/FieldSet.js
- src/components/input/FormField.js
- src/components/input/Info.js
- src/components/input/Input.scss
- src/components/input/Matrix/index.js
- src/components/project/index.js
- src/components/projectEdit/ProjectEdit.scss
-tooltip linked fields
-style bug fixes
> KAAV-966 Tiedon visualisointi - Tooltip

- src/components/common/Common.scss
- src/components/overview/styles.scss
> Style changes for an overview view.

- src/components/input/CustomInput.js
- src/components/input/DeadlineInfoText.js
-correct date formats to checks.
> KAAV-748 Aikataulujen muokkaus vaatii jossain tilanteessa väärää formaattia aikakenttiin

- public/locales/fi/translation.json
- src/components/RichTextEditor/index.js
- src/components/input/CustomInput.js
- src/sagas/projectSaga.js
-Prevent saving of empty textfields.
-Show error when trying to save empty textfield.
-Prevent empty input type text save.
-Prevent checking required fields to show false positives if only spaces are written on text fields.
> KAAV-849 Välilyönnit sallitaan merkkeinä

- src/components/common/Common.scss
- src/components/projectEdit/ProjectEdit.scss
> Toaster style fix.

- src/components/common/Common.scss
- src/components/project/Project.scss
- src/components/projectCard/projectCard.scss
- src/components/projectEdit/ProjectEdit.scss
> Style fixes for a project card view.

- src/components/projectEdit/quickNav/QuickNav.js
> Fixed an active phase indication in the phase select.

- src/components/common/Common.scss
- src/components/common/colors.scss
- src/components/projectEdit/ProjectEdit.scss
> Fix for a tooltip z-index issue.

- src/components/projectEdit/quickNav/QuickNav.js
> Fix for a phase selection when using the back arrow.

- public/locales/fi/translation.json
- src/components/common/Header.js
- src/components/common/colors.scss
- src/components/input/CustomCard.js
- src/components/input/CustomField.js
- src/components/input/FormField.js
- src/components/input/Input.scss
- src/components/projectEdit/EditForm.js
- src/components/projectEdit/FormSection.js
- src/components/projectEdit/index.js
- src/utils/infoFieldUtil.js
schedule and floor area info_field
> KAAV-972 schedule and floor area info_field

- src/components/common/Common.scss
> Fix for a field indicator styles.

- public/locales/fi/translation.json
- src/components/RichTextEditor/index.js
- src/components/common/Common.scss
- src/components/input/FormField.js
> Added an assitive text for form fields.

- src/components/input/CustomField.js
- src/components/projectDocuments/Document.js
- src/components/projectDocuments/DocumentGroup.js
- src/components/projectDocuments/index.js
- src/components/projectEdit/index.js
- src/sagas/projectSaga.js
- src/utils/projectUtils.js
-Document download check fixes.
-Prevent empty richtext linebreaks save.
-Current scheme section bug fix
> KAAV-996 document phases fix

- src/components/RichTextEditor/index.js
-Always show counter when focused to field.
-No limit to counter value.
> KAAV-1042 Mekkimäärälaskuri katoaa, kun 1001 merkkiä on ylitetty

- src/components/RichTextEditor/index.js
-Show error after onblur and when refocus happens, until error is gone.
> KAAV-1043 Merkkimäärä on ylittynyt -virheilmoitus katoaa, kun käyttäjä poistuu kentästä

- src/sagas/projectSaga.js
> Fix for a file upload.

- src/components/common/Common.scss
- src/components/common/colors.scss
- src/components/projectEdit/quickNav/styles.scss
> Scrollbar styles.

- src/components/input/CustomField.js
- src/components/input/DeadlineInput.js
- src/components/input/FormField.js
- src/components/project/EditProjectTimetableModal/index.js
-Fixed some deadline fields in schedule view had no calendar icons. KAAV-1059 
-Fixed could not be edited, fixed phase not over and in some situations date select is disabled anyway. KAAV-1035
> KAAV-1059 Päivämääräkentistä puuttuu kalenteri

- src/components/RichTextEditor/styles.scss
> KAAV-970  Tiedon visualisointi - Merkkimäärän rajoitus

- src/components/projectEdit/ProjectEdit.scss
- src/components/projectEdit/quickNav/QuickNav.js
- src/components/projectEdit/quickNav/styles.scss
> Fix for a scroll position issue (first render, navi selection).

- src/components/projectCard/projectCard.scss
> Fix for a card styles for the project card view.

- src/components/projectEdit/ProjectEdit.scss
> Style fix for a tooltip problem.

- src/components/common/Header.js
- src/components/input/CustomInput.js
- src/components/projectEdit/index.js
-show error toastr if has somekind of error on form fields
> KAAV-1060 Ilmoitus tulee jos tallennus on estynyt

- src/components/input/CustomField.js
- src/utils/infoFieldUtil.js
info field at start always visible even if it has no data
> KAAV-1080 Kerrosala-infolaatikon pitäisi näkyä vaikka kerrosalatietoja ei ole täytetty

- src/components/input/FormField.js
> Fix for an undefined issue inside the floor area modal.

- src/components/input/CustomField.js
- src/components/input/CustomInput.js
- src/sagas/projectSaga.js
-Img save or delete shows errors when it succesfuly saves or deletes fix. 
-added regex validation rules from excel to input fields and added logic to show error if regex validation exists and does not pass.
KAAV-561,1102,1110.
> KAAV-1102 Näytä virheet linkki ei focusoi virhe kohtaan aina

- src/components/input/CustomCard.js
…ation. Fixed a file name display issue when the image has an empty caption.
Issue: KAAV-1111
> Added a missing unit info for the floor area card.

- src/components/common/Common.scss
- src/components/input/Info.js
- src/components/input/Input.scss
> Fix for a tooltip visibility issue.

- src/components/input/CustomCard.js
-Added deadlineSelector to CustomCard updates so value change from generated to modified by user can registered to CustomCard after save
> KAAV-1084 Tieto ei päivity heti muutoksen jälkeen päivämäärän tarkistus -infolaatikkoon

- src/utils/infoFieldUtil.js
-hide custom card only if both checkboxes are confirmed
> KAAV-1083 Päivämäärien tarkastamisen infolaatikko poistuu liian aikaisin (päättymispäivää ei ole vahvistettu)

- src/components/RichTextEditor/index.js
-prevent un-needed unlock calls from project tools and last update  menu select buttons
> KAAV-1006 Turhien requestien suodattaminen pois

- src/components/common/Header.js
- src/components/input/FieldSet.js
- src/components/project/EditFloorAreaFormModal/index.js
- src/sagas/projectSaga.js
-Assistive test for fieldsets. [KAAV-561](https://helsinkisolutionoffice.atlassian.net/browse/KAAV-561)
-Do not show success toastr when image is saved. 
-Enable close modal from x button. https://helsinkisolutionoffice.atlassian.net/browse/KAAV-1117
[KAAV-561]: https://helsinkisolutionoffice.atlassian.net/browse/KAAV-561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAAV-1117   Kerrosalatietojen dialogin ruksi ei toimi

- src/components/common/Common.scss
- src/components/common/colors.scss
- src/components/input/FormField.js
- src/components/input/Input.scss
- src/components/input/Matrix/styles.scss
- src/components/projectEdit/FormFilter.js
- src/components/projectEdit/ProjectEdit.scss
- src/components/projectEdit/quickNav/QuickNav.js
- src/components/projectEdit/quickNav/styles.scss
> Styles for filters (Project edit view).

- src/components/RichTextEditor/styles.scss
- src/components/common/Common.scss
- src/components/input/Input.scss
- src/components/projectEdit/quickNav/styles.scss
> Styles for a navigation and a rich text editor.

- src/components/common/Common.scss
- src/components/input/Input.scss
> Styles for input fields hover/focus.

- src/components/input/CustomCard.js
- src/components/input/Input.scss
> Styles for a custom card.

- package.json
- yarn.lock
updated package crypto-js to lastest version that is depenfency of oidc-client pacakage
> KAAV-1268  Front kirjastojen tarkistus ja päivitys

- package.json
- yarn.lock
> KAAV-1268 KAAV-1268   Front kirjastojen tarkistus ja päivitys

- package.json
- yarn.lock
> KAAV-1268   Front kirjastojen tarkistus ja päivitys

- src/components/input/FieldSet.js
-disable add fieldset if there is errors in form
> KAAV-1155 Fieldset lukitus virhe luodessa kuva + pitkä teksti fieldset.

- src/components/input/FieldSet.js
- src/components/input/SelectInput.js
- src/sagas/projectSaga.js
-Empty select values to save as empty array not null.
-Multiselect values to show up as selected true if values have been selected earlier.
-Prevent selecting same value multiple times.
KAAV-1170,1182,1161
> KAAV-1170 Virheilmoitus puuttuvasta strategisten tavoitteiden valinnasta vaikka valinta on tehty

- src/components/input/CustomCard.js
- src/components/input/CustomField.js
Info card dates converted to correct format and changed correct starts and ends texts depending on what dates card is showing
> KAAV-1171   OAS:n vuorovaikutuksen suunnittelun kohdalla päivämäärien ehdotukset väärin

- src/components/input/RollingInfo.js
-Show username instead of user id on responsible person field.
> KAAV-1139 Vastuuhenkilön nimen tilalla näkyy vain numerosarja

- src/components/RichTextEditor/index.js
- src/components/input/Input.scss
- src/components/input/RollingInfo.js
-Rolling info richtexts to show edit format styles like in the actual edit mode.
> KAAV-1153 Vyöryneen tekstin ulkoasu ei ole saman näköinen kuin syötetyn tekstin ulkoasu

- src/components/input/FieldSet.js
- src/hooks/OutsideClick.js
-Fieldset accordian names to generate from first value of fieldset.
> KAAV-1098 Fieldsetin accordionin otsikkoon kentän arvo

- src/components/RichTextEditor/index.js
- src/components/common/Header.js
- src/components/input/CustomInput.js
-Show error toaster only once for specific error
> KAAV-1172 Sama kenttä luo useita virheilmoituksia

- src/assets/icons/Infobothdir.svg
- src/components/RichTextEditor/index.js
- src/components/input/CustomField.js
- src/components/input/CustomInput.js
- src/components/input/FieldSet.js
- src/components/input/FormField.js
- src/components/input/Link.js
- src/components/input/RadioBooleanButton.js
- src/components/input/RollingInfo.js
- src/components/input/SelectInput.js
- src/components/projectEdit/EditForm.js
- src/components/projectEdit/FormSection.js
- src/components/projectEdit/index.js
-New icons for rolling info, logic changes.
> KAAV-1135 Vyöryvät tiedot - Toteutus

- src/components/input/CustomInput.js
- src/sagas/projectSaga.js
-Modified yield save call to put and added needed parameters so phase close save works.
-Fixed error when typing name in create projekt input.
> KAAV-1292 "Lopeta vaihe" -painikkeesta ei tapahdu mitään (vaiheen lopettaminen ei onnistu)

- src/actions/projectActions.js
- src/components/projectEdit/index.js
- src/reducers/projectReducer.js
-Reset visible errors if phase/section navigation is pressed and prevent situation where saving gets disabled before page refresh.
> KAAV-1182 Laatikoita(accordion/fieldset) avatessa tulee virheilmoituksia

- public/locales/fi/translation.json
- src/components/input/CustomCard.js
- src/components/input/Input.scss
- src/utils/infoFieldUtil.js
-Lautakuntapäivät lisäys vaiheisiin (ehdotus ja tarkitettu ehdotus ei vielä excelissä).
-Tyyli muutokset
> KAAV-1119 - Päivämäärien tarkastus toteutus

- src/components/projectList/index.js
-expert or browser user role  not to have create project rights
> KAAV-1298 Asiantuntija näkee "Luo uusi projekti" -painikkeen (ei ole sallittua)

- src/components/input/CustomRadioButton.js
-On modify project create data, disable checkbox clicking for users that have only read rights.
> KAV-1299 Asiantuntija voi muokata, mutta ei tallentaa, luodun projektin tietoja (ei ole sallittua)

- src/components/projectEdit/index.js
-Unlock fields to happen when refreshing, going back to project card or clicking side navigation.
> KAAV-1101 Lukinnan purkautuminen variaatioilla (3 casea)

- public/locales/fi/translation.json
all projects text changed to active projects
> KAAV-1130 Termin muutos - Toteutus

- src/components/project/index.js
- src/components/projectEdit/index.js
- src/components/projectList/index.js
-fixed check for edit privilages
> KAAV-1335 Vastuuhenkilö ei voi muokata kerrosalatietoja

- src/components/RichTextEditor/index.js
- src/reducers/projectReducer.js
-Fieldset sometimes restores old values when editing with same user and on different tabs fix.
-Fieldset value not updating correctly on some cases fix.
> KAAV-801 Fieldset editointi palauttaa vanhan arvon

- src/utils/infoFieldUtil.js
-Info card dates are shown empty fix
> KAAV-1308 Aikataulun päivittämisen päivämäärät eivät tallennu (lieveilmiö KAAV-1292:sta ?)

- src/components/common/Common.scss
- src/components/projectDocuments/Document.js
- src/components/projectDocuments/ProjectDocuments.scss
> Font size fixes for a last loaded text and h1.

- public/locales/fi/translation.json
- src/components/input/File.js
- src/components/input/Input.scss
> Removed a description functionality from the file component.

- src/components/input/CustomField.js
- src/components/input/CustomInput.js
-Error text from excel to show if in data.
> KAAV-561   Kentät, mitkä pitää validoida ja niiden säännöt

- src/components/RichTextEditor/index.js
- src/components/input/CustomInput.js
-Prevent offline edit if field was not locked for user before going offline. Prevents saving when returning from offline without fetching previous edits from other users first and checking lock status.
> KAAV-1347 B:n tietokantaan tallennetut muutokset ylikirjoitetaan, kun A:n offline yhteys palautuu

- src/components/project/index.js
-Project card download button extracted out from select dropdown
> KAAV-1351 Projektikortti - muutokset otsikkorivin painikkeisiin

- src/components/input/DeadlineInfoText.js
-if timetable deadline info date is array then use initial value.
> KAAV-1353 Ehdotuksen nähtävilläolon pituuden päivämäärä (kokonaisluku) näytetään virheellisesti -> estää etenemisen

- src/components/input/CustomCard.js
-Removed extra brackets from variable already inside brackets in custom card
> KAAV-1361 Jotkut väliotsikot ohjaavat tyhjään näkymään

- src/utils/infoFieldUtil.js
-Suggestion phase timetable card logic to read both large and small project variables from Excel.
> KAAV-1371 Ehdotus -vaiheen projektissa päivämäärien infolaatikossa näkyy vain nähtävilläolon päättymispäivä.

- src/components/App.js
> KAAV-1377 Matamo analytiikka käyttöönotto

- src/components/App.js
- src/components/project/EditProjectTimetableModal/index.js
-Fixed timetable modal shows values in wrong order. KAAV-1250
-Matomo container added.
> KAAV-1381 

- src/components/project/EditProjectTimetableModal/index.js
- simplify frontend because fixed in backend import
> KAAV-1250 Aikataulun muokkausnäkymässä vahvista kaavehdotuksen päättyminen –boksi väärässä kohdassa

- src/actions/projectActions.js
- src/components/App.js
- src/components/input/FieldSet.js
- src/components/projectEdit/EditForm.js
- src/reducers/projectReducer.js
- src/sagas/projectSaga.js
- src/selectors/projectSelector.js
- src/utils/api.js
- yarn.lock
-Refresh single attribute data logic.
-Update and add fieldset.
-Replace lodash pick with lodash.
-Redux form keepDirtyOnReinitialize to false.
> KAAV-1394 Fieldset ylikirjoitus

- src/components/App.js
-Updated code to use other providers Matomo.
> KAAV-1377   Matamo analytiikka käyttöönotto

- public/locales/fi/translation.json
> KAAV-1325 Kirjoitusvirhe: Dokumentit näkymässä "kaavoitussihteri"

- src/components/input/FieldSet.js
-Extract name from email info for fieldset header, intead of id.
> KAAV-1295 Fieldseteissä näkyy nimen sijasta numerosarja

- src/actions/documentActions.js
- src/components/projectDocuments/Document.js
- src/components/projectDocuments/DocumentGroup.js
- src/components/projectDocuments/index.js
- src/reducers/documentReducer.js
- src/sagas/documentSaga.js
- src/selectors/documentSelector.js
-Prevent start of multiple document download because last one is only downloaded.
> KAAV-1336 Vaiheen voi sulkea, vaikka asiakirjat eivät ole tallentuneet koneelle (lataus kesken?)

- src/actions/projectActions.js
- src/components/input/FieldSet.js
- src/sagas/projectSaga.js
-Refresh fieldset data before removing/hiding sub fieldset.
> KAAV-1408 Fieldset ylikirjoitus (poisto)

- src/components/input/CustomField.js
- src/components/input/FieldSet.js
- src/components/input/File.js
- src/components/input/Input.scss
> KAAV-1320 Vyöryvien tietojen infoteksti puuttuu fieldseteistä

- src/components/input/CustomCheckbox.js
KAAV-1416/KAPI-20
-Enable the change of xl principles and draft phases sent to board checkbox in timetable modal.
> KAAV-1416 Viedäänkö kaavamuutos lautakuntaan ei voi editoida

- src/components/ProjectTimeline/ProjectTimeline.jsx
-Project timeline shows milestone month 12 as 0 fix.
> KAAV-1412 Aikataulujanalla Kylk-päivämäärä näkyy muodossa 3.0. (eikä 3.12.)

- src/sagas/projectSaga.js
-Use array values for overview floor area choice filtering.
> KAAV-1390 Yleisnäkymän graafien suodatuksien puutteet

- src/components/projectEdit/index.js
document link to scroll to correct field
> KAAV-1275 Dokumentin linkistä ei pääse Kaavapinon muokkausnäkymään

- src/components/input/CustomInput.js
- src/components/input/RollingInfo.js
-If no info from facta on building pertmis to show text Ei ole and others to show Ei instead of Tieto puuttuu
> KAAV-1271 Rakennuskieltojen puuttuminen tekstinä "Ei ole"

- src/components/input/CustomField.js
- src/components/input/FieldSet.js
-Fieldset rolling info buttons to be disabled instead of hidden when uneditable
> KAAV-1125 Vyöryvien tietojen muutos (v1.0.1)

- public/locales/fi/translation.json
- src/components/projectCard/Documents.js
- src/components/projectCard/index.js
-Map link from edit form to showup in project card documentsview.
> KAAV-1462 Karttapalvelun linkki ei siirry projektikorttiin

- src/components/input/CustomField.js
- src/components/input/FieldSet.js
> KAAV-1183 Tietue on vieras termi

- src/components/reports/FilterField.js
- src/sagas/projectSaga.js
-KAAV-1322 Reports floor area select to show value that is selected.
-KAAV-1491 Timetable and floor area modal to show toastr error when internet has gone down.
> KAAV-1322 Toimintasuunnitelma-raportin suodattimet eivät toimi / suodata kaikkia tietoja

- src/components/projectEdit/index.js
- src/components/projectEdit/quickNav/QuickNav.js
-Document urls to redirect to correct section and title.
-Removed commented out code.
> KAAV-1275 KAAV-1275   Dokumentin linkistä ei pääse Kaavapinon muokkausnäkymään

- public/locales/fi/translation.json
- src/components/input/CustomCard.js
- src/components/input/CustomField.js
- src/utils/infoFieldUtil.js
> KAAV-1348 Päivämäärän merkitsemistä koskeva info-laatikko Hyväksyminen-vaiheeseen

- src/components/RichTextEditor/index.js
Added filtering with project ID for field comments.
> KAAV-437 fix other projects comments showing after editing comment

- src/components/input/CustomCard.js
- src/components/input/CustomField.js
- src/utils/infoFieldUtil.js
-Voimaantulo and Muutoksenhaku custom info boxes.
> KAAV-1943 Voimaantulovaiheen infolaatikko (yksi tai kaksi)

- src/components/ProjectTimeline/VisTimelineGroup.js
- src/components/project/EditProjectTimetableModal/index.js
Matches a deadline's group to a boolean value, which determines whether the subgroup is added.
_**Lautakunta subgroups are waiting for an excel change**_ and will not be displayed until it is implemented (except for 1st one)
> KAAV-2102 Set visibility of subgroups based on bool values

- package.json
- yarn.lock
Fixes:
https://github.com/City-of-Helsinki/kaavapino-ui/security/dependabot/115[High](https://github.com/City-of-Helsinki/kaavapino-ui/security/dependabot?q=is%3Aopen+severity%3Ahigh)
#115 opened 2 months ago • Detected in body-parser (npm) • yarn.lock
https://github.com/City-of-Helsinki/kaavapino-ui/security/dependabot/111[High](https://github.com/City-of-Helsinki/kaavapino-ui/security/dependabot?q=is%3Aopen+severity%3Ahigh)
#111 opened 2 months ago • Detected in path-to-regexp (npm) • yarn.lock
https://github.com/City-of-Helsinki/kaavapino-ui/security/dependabot/110[High](https://github.com/City-of-Helsinki/kaavapino-ui/security/dependabot?q=is%3Aopen+severity%3Ahigh)
#110 opened 2 months ago • Detected in path-to-regexp (npm) • yarn.lock …
> KAAV-2324 package updates

- src/components/App.js
-Limit Matomo analytics to prod env.
> KAAV-1627 Matomon seurannan suorituskykyongelman korjaaminen

- src/utils/timeUtil.js
-nahtavillaolo and esillaolo Date comparison modifications to calendar.
> KAAV-2525 nahtavillaolo and esillaolo timeutil improvements

- src/components/project/EditProjectTimetableModal/index.js
Added check when changing phase, vis timeline item start date must have value or not added to data.
> KAAV-2718 Aikataulunmuokkaus whitescreen kun projektin kokoluokka M -> L

- src/components/input/CustomInput.js
- src/components/input/DeadlineInput.js
- src/utils/timeUtil.js
-KAAV-3012-14.
-Tarkistettu ehdotus 2-4 to have correct minium dates in calendar selections.
-Fixed whitescreen when editing hyvaksyminen calendar dates.
-hyvaksymis numero readonly bug fix.
> KAAV-3013 pre-UAT-3 fixes

- src/components/ProjectTimeline/VisTimelineGroup.jsx
- src/components/ProjectTimeline/VisTimelineMenu.jsx
-Timeline zoom 2 years, 3 months and 6 months.
> KAAV-3120 Zoomaustasojen lisäys
