- src/components/input/CustomField.js
- src/components/input/FieldSet.js
Relates to issue where "suunnittelualueella_kiinteisto_fieldset" is updated with properties fetched from Kaavoitus-API
> Added _automatically_removed property to disable automatically fetched fieldsets

- src/components/RichTextEditor/index.js
- src/components/input/CustomInput.js
- src/components/input/FormField.js
-rich text editor ref instead of state onchange because we do not need re render after value change
> Kaav 440 Näkymän kaikki kentät renderöivät kun yhtä kenttää muokkaa

- src/__tests__/components/input/Input.test.js
- src/actions/projectActions.js
- src/components/RichTextEditor/index.js
- src/components/input/CustomField.js
- src/components/input/CustomInput.js
- src/components/input/CustomTextArea.js
- src/components/input/FormField.js
- src/components/input/SelectInput.js
- src/reducers/projectReducer.js
- src/sagas/projectSaga.js
-prevent writing to input fields when locked and onchange to happen for first keypress. Prevent lock and unlock field call order getting mixed and sometimes locking and unlocking the same field wrongly
> Kaav 497 improvements

- src/components/RichTextEditor/index.js
-added check to richtext onfocus for copy paste and prevent toolbar and lock again then.
> KAAV-616 Kopioimalla liitetty teksti menee piiloon tekstikentässä ja häviää, kun käyttäjä kirjoittaa lisää tekstiä. 

- src/sagas/reportSaga.js
-Report sagas text response types changed to json. Needed on latests versions of document related libraries on project.
> KAAV-686 Lataa raportti .xlsx- ja Esikatselu -toiminnot eivät toimi

- src/components/RichTextEditor/index.js
- src/utils/projectUtils.js
-Fixed richtext editor object comparison and richtext cursor always focusing to start of the editor when clicking.
> KAAV-929 Tekstikentän tekstiosoitin pomppaa jatkuvasti kentän alkuun

- src/components/RichTextEditor/index.js
- src/sagas/projectSaga.js
prevent routing to error 500 if unlock happens to return multiple attributelock, instead record error and conntinue editing and saving normally.
> KAAV-981 Projektiin täytetyt tiedot eivät tallentuneet

- src/components/input/CustomInput.js
- src/sagas/projectSaga.js
-delete attribute_data.oikaisukehoituksen_alainen_readonly when saving dates, is blocking when is set true and is not needed in this data. 
-KAAV-849 input error fields showing when not editing and is empty bug fix.
> KAAV-748 Aikataulujen muokkaus vaatii jossain tilanteessa väärää formaattia aikakenttiin

- src/sagas/projectSaga.js
prevent _readonly attributes to save again
> KAAV-1092 Luonnos vaiheen Vaikutukset -osion alla ei pääse eteenpäin

- src/components/RichTextEditor/index.js
- src/components/input/CustomCard.js
- src/components/input/CustomField.js
- src/components/input/CustomInput.js
- src/components/input/FormField.js
- src/components/input/Link.js
- src/components/input/RadioBooleanButton.js
- src/components/input/RollingInfo.js
- src/components/input/SelectInput.js
- src/components/project/EditFloorAreaFormModal/index.js
- src/components/project/EditProjectTimetableModal/index.js
- src/components/projectEdit/EditForm.js
- src/components/projectEdit/FormSection.js
- src/components/projectEdit/index.js
- src/reducers/projectReducer.js
- src/utils/infoFieldUtil.js
-Info field dates to hide if dates are confirmed. KAAV-1083
-Richtext disable right click copy paste and toolbar buttons  when locked.  KAAV-1100, KAAV-1107
-Disable rolling info buttons if phase has passed and is not starting phase. KAAV-967
-Hide rolling info text if phase is no longer editable. KAAV-967
-Custom card not updating when modal data is saved fix. KAAV-1084
-Edit floor area and timetable modal not to render twice, moved closing logic from save floor area and timetable to save success reducer so separate close call after save is not needed, cleaned not needed calls from floor area and timetable due to changes.
> KAAV-1083 Päivämäärien tarkastamisen infolaatikko poistuu liian aikaisin (päättymispäivää ei ole vahvistettu)

- src/components/input/RollingInfo.js
-Disable rolling info button instead of hiding it.
-Hide rolling info text when phase has ended or in first phase.
> KAAV-1125 Vyöryvien tietojen muutos

- src/components/RichTextEditor/index.js
-Richtext charlimit over error not resetting and preventing save fix.
> KAAV-1276 Merkkimäärän ylityksen jälkeen mikään kenttä ei tallennu vaikka virheen korjaa

- src/components/input/SelectInput.js
- src/sagas/documentSaga.js
-KAAV-1112 Rollinginfo selects to show value labels instaead of value ids to user.
-KAAV-1206 toastr to be visible untill download is ready
> KAAV-1112 Pudotusvalikosta valittu vaihtoehto näkyy virheellisesti tunnisteen muodossa

- public/locales/fi/translation.json
- src/components/projectEdit/FormSection.js
> Fixed the no fields text and added it to the translation.json.

- src/components/projectEdit/quickNav/QuickNav.js
When navigating to different phase from side navigation menu, always start from section 0.
> KAAV-1049 Navigaatiosta valittu otsikko ei vastaa kenttäalueen otsikkoa

- src/components/RichTextEditor/index.js
-Bullet and number list removed from richtext editor options.
> KAAV-1149 Ala- ja yläindeksit (ok) sekä luettelomerkit eivät näy luoduissa word dokumenteissa

- public/locales/fi/translation.json
- src/components/input/CustomCard.js
disable editform timetable card  edit button when all confirm boxes are selected
> KAAV-1396 Infolaatikko: vahvistetuille päivämäärille näkyy yhä "Muokkaa päivämääriä" -painike (vaikka ei pitäisi)

- src/components/input/CustomCard.js
- src/utils/infoFieldUtil.js
-Timetable card values to be in reverse order in suggestion phase
> KAAV-1395 Infolaatikko: ehdotusvaiheen esilläolopäivät tulisi näyttää KYLK-päivän jälkeen L-XL-kokoluokan kaavoissa.

- src/components/project/EditProjectTimetableModal/index.js
-Timetable modal richtext fields not getting attribute_data fix.
> KAAV-1496 Aikataulujen muokkaus ohjaa tyhjään näkymään

- src/components/ProjectTimeline/VisTimeline.scss
- src/components/ProjectTimeline/VisTimelineGroup.js
- src/components/input/DeadlineInput.js
- src/components/project/EditProjectTimetableModal/index.js
This ensures that newly added groups are consistent with groups formed during initial render.
For some reason, this approach gives the vis-group-level-0 CSS class to nested deadlines (which should be impossible?), added style rules to accommodate.
> KAAV-2073 Change group add to work through getTimelineData, fix newly added groups not updating on timeline

- public/locales/fi/translation.json
- src/sagas/projectSaga.js
- src/utils/timeUtil.js
-Timeline 2-4  board to not use first board minium values.
-Validation failure to show own error message instead of general save error.
> KAAV-3016 Pre-UAT3: Kaikki vaiheeet 2. lautakuntakerran osa päivistä ei ole valittavissa
